### ISSUE TITLE
inferno-create-class in devDependencies

### ISSUE THREAD

**Issue by SuhairZain** [infernojs/inferno-motion#4]
Hi,
I was trying to use inferno-motion in one of my apps and when I imported it, webpack showed an error that the package inferno-create-class is missing. I checked the package.json for inferno-motion, and inferno-create-class is listed as a devDependency, meaning it won't be installed when inferno-motion is installed. I then installed inferno-create-class to my app and now it's working properly.

Is inferno-create-class only a dev time dependency for inferno-motion? In that case, webpack shouldn't have reported that error. In case it's not, shouldn't it be a part of dependencies rather than devDependencies?

**Comment by lukeed** [comment]
Hey @SuhairZain You are correct 😄 

@Havunen will see the change shortly & publish a new patch release for you. I do not have NPM access to this particular package, otherwise I'd go ahead.
